<a href="https://colab.research.google.com/github/Marudivishnu123/Marudivishnu123/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
a = np.array([[1,2,3,4],[6,7,8,9]])
print(a)
print(a[0])
print(a[1])
print(a[0,2:])
print(a[1,1:3])



[[1 2 3 4]
 [6 7 8 9]]
[1 2 3 4]
[6 7 8 9]
[3 4]
[7 8]


In [6]:
b = np.array([1,2,3,4,4])
print(b)

[1 2 3 4 4]


# now we will do with the 3 dimensional arrays in this numpy ntg  if  in a single list if we have two or moore two dimensional array then it is called as 3 dimensional array


In [7]:
c = np.array([[[1,2],[3,4]],[[6,7],[8,9]]])
print(c)

[[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]]


In [8]:
c.ndim

3

# get a specific element in the 3 dimensional array


In [9]:
c[0][1]


array([3, 4])

In [12]:
%%timeit
c[0][1][0]

604 ns ± 174 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
